fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: 2.4.0
    zypprepo: "git://github.com/deadpoint/puppet-zypprepo.git"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile.git"
    archive: "git://github.com/voxpupuli/puppet-archive.git"
  symlinks:
    php: "#{source_dir}"
